project:
  type: book
  output-dir: docs

book:
  title: "Improved 21st century projections of sub-daily extreme precipitation by spatio-temporal recalibration"
  author: "Brynjólfur Gauti Guðrúnar Jónsson"
  repo-url: "https://github.com/bgautijonsson/phd"
  date: "29/08/2022"
  chapters:
    - index.qmd
    - part: "Models"
      chapters:
        - "Projects/Modeling/Max & Smooth/index.qmd"
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo